# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - springeye
  categories:
    - title: Feature 🛠
      labels:
        - feature
    - title: Fix 🎉
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
